//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNS.Accounts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public Nullable<decimal> Cr { get; set; }
        public Nullable<decimal> Dr { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
