// <auto-generated />
namespace iFinco.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class role_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(role_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201802180934210_role_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
