// <auto-generated />
namespace iFinco.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Owner_Check_and_Status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Owner_Check_and_Status));
        
        string IMigrationMetadata.Id
        {
            get { return "201802150633568_Owner_Check_and_Status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
