// <auto-generated />
namespace iFinco.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_Branch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Branch));
        
        string IMigrationMetadata.Id
        {
            get { return "201801282026062_User_Branch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
