//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iFinco.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generalinvoice
    {
        public long Id { get; set; }
        public Nullable<long> PartyId { get; set; }
        public long InvoiceNum { get; set; }
        public decimal Amount { get; set; }
        public int Type { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> BranchId { get; set; }
        public long CompanyId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
