//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iFinco.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iFincoDBEntities : DbContext
    {
        public iFincoDBEntities()
            : base("name=iFincoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<GoDown> GoDowns { get; set; }
        public virtual DbSet<Variant> Variants { get; set; }
        public virtual DbSet<VariantValue> VariantValues { get; set; }
        public virtual DbSet<ProductVariant> ProductVariants { get; set; }
        public virtual DbSet<ProductAttributeCombination> ProductAttributeCombinations { get; set; }
        public virtual DbSet<PACDetail> PACDetails { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<BranchAccess> BranchAccesses { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual DbSet<SaleDetail> SaleDetails { get; set; }
        public virtual DbSet<PurchaseReturn> PurchaseReturns { get; set; }
        public virtual DbSet<ShippingDetail> ShippingDetails { get; set; }
        public virtual DbSet<CompanyMenusAccess> CompanyMenusAccesses { get; set; }
        public virtual DbSet<SaleReturn> SaleReturns { get; set; }
        public virtual DbSet<PurchaseReturnDetail> PurchaseReturnDetails { get; set; }
        public virtual DbSet<SaleReturnDetail> SaleReturnDetails { get; set; }
        public virtual DbSet<Generalinvoice> Generalinvoices { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<InvoiceTemplate> InvoiceTemplates { get; set; }
        public virtual DbSet<PlaceHolder> PlaceHolders { get; set; }
    }
}
