//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iFinco.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACDetail
    {
        public long Id { get; set; }
        public long PACId { get; set; }
        public long VariantId { get; set; }
        public long VariantValueId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ProductAttributeCombination ProductAttributeCombination { get; set; }
        public virtual Variant Variant { get; set; }
        public virtual VariantValue VariantValue { get; set; }
    }
}
