//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iFinco.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingDetail
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> SaleId { get; set; }
        public Nullable<long> PurchaseId { get; set; }
        public Nullable<long> ShipmentNo { get; set; }
        public string Address { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
