//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iFinco.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public long Id { get; set; }
        public decimal Quantity { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal PurchasingPrice { get; set; }
        public string Code { get; set; }
        public string BarCode { get; set; }
        public string BarCodeImgUrl { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public long ProductId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> GodownId { get; set; }
        public Nullable<long> PACId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual GoDown GoDown { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductAttributeCombination ProductAttributeCombination { get; set; }
    }
}
